# These are supported funding model platforms

github: Pondsi
custom:
  - https://paypal.me/pondsi
  - https://github.com/Pondsi/wenyanskill/blob/main/sponsors/wechat-pay.jpg
  - https://github.com/Pondsi/wenyanskill/blob/main/sponsors/alipay.jpg
