# These are supported funding model platforms

github: Pondsi
patreon:
open_collective:
ko_fi:
tidelify:
custom:
  - https://github.com/Pondsi/wenyanskill/blob/main/sponsors/wechat-pay.jpg
  - https://github.com/Pondsi/wenyanskill/blob/main/sponsors/alipay.jpg
